#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo "--> ACTION HOOK: post_deploy <--"
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

python celery -A curriculumBuilder worker -l info &