language: python
python: 2.7
cache: pip

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-server-dev-9.6

before_install:
  - sudo apt-get install -y libgnutls28-dev

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - export PATH="$PATH:$PYTHONPATH:$(pwd):./node_modules/.bin:./.heroku/vendor/bin"
  - psql -c 'create database curriculumbuilder;' -U postgres
  - python manage.py migrate

script:
  - debug=true python manage.py test
